name: Gofi Release

on:
  create:
    branches:
      - master
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 获取触发TAG
      - name: Obtain Trigger Tag
        id: tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      # 打印触发TAG
      - name: Echo Trigger Tag
        run: echo Trigger tag is ${{ steps.tag.outputs.VERSION }}

      # 拉取xgo docker镜像
      - name: Pull xgo docker image
        run: docker pull techknowlogick/xgo:latest

      # 检出对应TAG的代码
      - name: Checkout Trigger Branch
        uses: actions/checkout@v1

      # 执行构建脚本
      - name: Excute Build Script
        run: ./build.sh

      # 创建新的发布
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.VERSION }}
          release_name: Release ${{ steps.tag.outputs.VERSION }}
          draft: false
          prerelease: false

      # 上传构建产物到发布
      - name: Upload Build Outputs
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./output/gofi-${{ steps.tag.outputs.VERSION }}-android-16-arm
            ./output/gofi-${{ steps.tag.outputs.VERSION }}-darwin-10.6-amd64
            ./output/gofi-${{ steps.tag.outputs.VERSION }}-linux-amd64
            ./output/gofi-${{ steps.tag.outputs.VERSION }}-linux-arm-5
            ./output/gofi-${{ steps.tag.outputs.VERSION }}-windows-4.0-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
