name: Gofi Release

on:
  create:
    branches:
     - master
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 安装Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v1

      # 安装Yarn
      - name: Setup Yarn
        run: npm install -g yarn

      # 安装go
      - name: Setup Golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      # 获取触发TAG
      - name: Obtain Trigger Tag
        id: tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      # 打印触发TAG
      - name: Echo Trigger Tag
        run: echo Trigger tag is ${{ steps.tag.outputs.VERSION }}

      # 检出对应TAG的代码
      - name: Checkout Trigger Branch
        uses: actions/checkout@v1

      # 执行构建脚本
      - name: Excute Build Script
        run: ./build.sh

      # 创建新的发布
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.VERSION }}
          release_name: Release ${{ steps.tag.outputs.VERSION }}
          draft: false
          prerelease: false

      # 上传构建产物到发布
      - name: Upload Build Outputs
        uses: softprops/action-gh-release@v1
        with:
          files: |
            # linux
            ./output/gofi-linux-amd64
            ./output/gofi-linux-386
            ./output/gofi-linux-arm
            # macOS
            ./output/gofi-macOS-amd64
            ./output/gofi-macOS-386
            # freebsd
            ./output/gofi-freebsd-amd64
            ./output/gofi-freebsd-386
            # windows
            ./output/gofi-windows-amd64.exe
            ./output/gofi-windows-386.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
